# Generated by Django 6.1 on 2026-08-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_rooms_options_rooms_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-added']},
        ),
    ]
